version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: vonage-status-panel, grafana-clock-panel
      GF_PANELS_DISABLE_SANITIZE_HTML: 'true'
    user: "472"
    links:
      - influx
  influx:
    image: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: test
      INFLUXDB_USER: test
      INFLUXDB_USER_PASSWORD: test

