version: '3'

services:
  grafana:
    build:
      context: .
      dockerfile: grafana.Dockerfile
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_PANELS_DISABLE_SANITIZE_HTML: 'true'
      INFLUXDB_DB: test
      INFLUXDB_USER: test
      INFLUXDB_USER_PASSWORD: test
      INFLUX_HOST: influx
      GF_SECURITY_ADMIN_PASSWORD: password
    user: "472"
    links:
      - influx
  influx:
    image: influxdb:1.8.10-alpine
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: test
      INFLUXDB_USER: test
      INFLUXDB_USER_PASSWORD: test
  # strava:
  #   image: strava:local
  #   environment:
  #     DB_DATABASE: test
  #     DB_USERNAME: test
  #     DB_PW: test
  #     DB_HOST: influx
  #     LOG_PATH: /proc/1/fd/1
  #   links:
  #     - influx
  #   volumes:
  #     - "./assets/secrets.yml:/app-src/assets/secrets.yml"
