version: '3'

services:
  grafana:
  # docker build . -f grafana.Dockerfile -t grafana:local
    image: grafana:local
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_PANELS_DISABLE_SANITIZE_HTML: 'true'
      INFLUXDB_DB: test
      INFLUXDB_USER: test
      INFLUXDB_USER_PASSWORD: test
      INFLUX_HOST: influx
    user: "472"
    links:
      - influx
  influx:
    image: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: test
      INFLUXDB_USER: test
      INFLUXDB_USER_PASSWORD: test

