{
 "title": "Strava Dashboard",
 "time": { "from": "now/y -5y", "to": "now" },
 "templating": {
  "list": [
   { "name": "type", "label": "Activity Type", "query": "select type from activities" }
  ]
 },
 "panels": [
  { "title": "Weeklys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "No of activities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "activities",
     "query": "SELECT count(\"distance\") FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/) ",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Distance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "activities",
     "query": "SELECT sum(\"distance\") FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "activities",
     "query": "SELECT sum(\"duration\") FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Elevation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT sum(\"elevation\") FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
     "select": [
      [
       { "params": [ "elevation" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Yearlys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Yeardistance",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT sum(\"distance\") FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Longest Ride",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT \"distance\" FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT \"max_speed\" FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
     "select": [
      [
       { "params": [ "max_speed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Elevation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT \"elevation\" FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
     "select": [
      [
       { "params": [ "max_speed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max max Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT \"max_watts\" FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
     "select": [
      [
       { "params": [ "max_speed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "No of activities",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "activities",
     "query": "SELECT count(\"distance\") FROM \"activities\" WHERE $timeFilter GROUP BY \"type\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rides",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT \"distance\", \"duration\" FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Totaldistance",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "measurement": "activities",
       "query": "SELECT \"distance\" FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
       "select": [
        [
         { "params": [ "distance" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Totaltime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "measurement": "activities",
       "query": "SELECT \"duration\" FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Number of Activities",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "measurement": "activities",
       "select": [
        [
         { "params": [ "avg_speed" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Longest Ride",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "measurement": "activities",
       "query": "SELECT \"distance\" FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
       "select": [
        [
         { "params": [ "distance" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Max Elevation",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "7d" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "activities",
       "query": "SELECT \"elevation\" FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
       "select": [
        [
         { "params": [ "distance" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Max Speed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "measurement": "activities",
       "query": "SELECT \"max_speed\" FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
       "select": [
        [
         { "params": [ "max_speed" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Max Power",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "measurement": "activities",
       "select": [
        [
         { "params": [ "max_watts" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "stat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "segments",
       "query": "SELECT min(\"prtime\") as time FROM \"segments\" WHERE $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "prtime" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Yearly Distances",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_year",
       "groupBy": [
        { "params": [ "year" ], "type": "tag" }
       ],
       "measurement": "activities",
       "query": "SELECT sum(\"distance\") FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)  GROUP BY \"year\"",
       "select": [
        [
         { "params": [ "distance" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Yearly Distance Progress",
     "type": "graph",
     "gridPos": { "h": 10, "w": 16, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "yaxes": [
      { "format": "lengthm" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "year" ], "type": "tag" }
       ],
       "measurement": "activities",
       "query": "SELECT cumulative_sum(\"distance\") as distance, cumulative_sum(\"elevation\") as elevation FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)  GROUP BY \"year\"",
       "select": [
        [
         { "params": [ "distance" ], "type": "field" },
         {
          "params": [],
          "type": "cumulative_sum"
         }
        ],
        [
         { "params": [ "elevation" ], "type": "field" },
         {
          "params": [],
          "type": "cumulative_sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Activity Heatmap",
     "type": "neocat-cal-heatmap-panel",
     "gridPos": { "h": 19, "w": 8, "x": 16, "y": 54 },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "activities",
       "query": "SELECT sum(\"distance\") FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/) GROUP BY time(24h) fill(null)",
       "select": [
        [
         { "params": [ "distance" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "$tag_year",
       "query": "SELECT cumulative_sum(\"duration\") as \"duration\" FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)  GROUP BY \"year\""
      }
     ]
    }
   ]
  }
 ]
}