{
 "title": "Yearly",
 "time": { "from": "2020-12-31T23:00:00.000Z", "to": "2021-12-31T22:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "type", "label": "Activity Type", "query": "select type from activities" }
  ]
 },
 "panels": [
  {
   "title": "Longest Ride",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT max(\"distance\") FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT max(\"max_speed\") FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
     "select": [
      [
       { "params": [ "max_speed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hours this Week",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "activities",
     "query": "SELECT sum(\"duration\") FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/) GROUP BY time(7d) fill(previous)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "7  avg distance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "activities",
     "query": "SELECT mean(\"distance\") FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/) GROUP BY time(7d) fill(previous)",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "7 Day avg of rides",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "activities",
     "query": "SELECT count(\"distance\") FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/) GROUP BY time(7d) fill(previous)",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Yeardistance",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT sum(\"distance\") FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rides",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "measurement": "activities",
     "query": "SELECT \"distance\", \"duration\" FROM \"activities\" WHERE $timeFilter AND (type =~ /^${type}$/)",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}